- name: installing nginx
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: state the nginx
      ansible.builtin.service:
        service: nginx
        state: started
        enabled: yes