- name: installing nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the nginx
    ansible.builtin.service:
      service: nginx
      state: started
      enable: yes
  - name: restart the ninx
    ansible.builtin.service:
      service: nginx
      state: restart

    